info:
  name: product
  type: http
  seq: 9

http:
  method: GET
  url: "{{base_url}}/user/organization/:pharmacy/product"
  headers:
    - name: Accept
      value: application/json
  params:
    - name: pharmacy
      value: 9d50ae23-fcff-4f4e-9384-ce0d10be17d6
      type: path
  auth:
    type: bearer
    token: 64|wekxmT6fEC7W1savxR3VWd2fcLOu9fkY2pdTExtBe40532c7

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

examples:
  - name: product
    request:
      url: "{{base_url}}/user/organization/:pharmacy/product"
      method: GET
      headers:
        - name: Accept
          value: application/json
      params:
        - name: pharmacy
          value: 9d50ae23-fcff-4f4e-9384-ce0d10be17d6
          type: path
    response:
      status: 200
      statusText: OK
      headers:
        - name: Date
          value: Wed, 23 Oct 2024 15:48:41 GMT
        - name: Server
          value: Apache/2.4.54 (Win64) OpenSSL/1.1.1d mod_fcgid/2.3.10-dev
        - name: X-Powered-By
          value: PHP/8.2.17
        - name: Cache-Control
          value: no-cache, private
        - name: X-RateLimit-Limit
          value: "60"
        - name: X-RateLimit-Remaining
          value: "59"
        - name: Access-Control-Allow-Origin
          value: "*"
        - name: Vary
          value: Authorization
        - name: Keep-Alive
          value: timeout=5, max=100
        - name: Connection
          value: Keep-Alive
        - name: Transfer-Encoding
          value: chunked
        - name: Content-Type
          value: application/json
      body:
        type: json
        data: |-
          {
              "success": true,
              "code": 0,
              "locale": "en",
              "message": "success",
              "data": {
                  "data": {
                      "id": "9d50ae23-fcff-4f4e-9384-ce0d10be17d6",
                      "service_id": "9d1e8559-091d-4a18-8b4b-bb7d281e68f5",
                      "item_number": "#O00001",
                      "quantity_in_stock": "2",
                      "is_in_stock": 1,
                      "organization_id": "9bc5eb78-74d2-45f4-a677-05d07dca6a63",
                      "inventory_id": "9d1e8ec9-769f-4967-88b6-109910f91d18",
                      "category": "string",
                      "description": "string",
                      "re_order_level": "50.00",
                      "status": "low_stock",
                      "unit_price": "3699.00",
                      "created_at": "2024-10-23T15:47:25.000000Z",
                      "updated_at": "2024-10-23T15:47:25.000000Z",
                      "service": {
                          "id": "9d1e8559-091d-4a18-8b4b-bb7d281e68f5",
                          "name": "Propranolol",
                          "service_type": "medicines",
                          "created_at": "2024-09-28T17:21:57.000000Z",
                          "updated_at": "2024-09-28T17:21:57.000000Z",
                          "organization_id": null,
                          "description": null,
                          "category": null,
                          "status": "active"
                      }
                  }
              }
          }
